### ISSUE TITLE
[NumberGuesser] Скучные ругательства

### ISSUE THREAD

**Issue by pavel-b-novikov** [IvanProkopyev/nsudotnet#1]
Да что ж вы все делаете исключительно конкатенацию слева/справа когда у вас есть в руках более мощные инструменты для вставки имени пользователя в середину ругательств.. Разнообразьте.

**Comment by IvanProkopyev** [comment]
Исправил.

**Comment by pavel-b-novikov** [comment]
Нет, не исправили. 
К тому же - вы зачем массив с цитатами создаете заново при каждом вызове метода?

**Comment by IvanProkopyev** [comment]
Исправил что касается массива. Так у меня же есть ругательства со вставкой в середину

**Comment by pavel-b-novikov** [comment]
Теперь вижу. Но массив все равно создается каждый б-жий вызов метода

**Comment by IvanProkopyev** [comment]
исправился.
