### ISSUE TITLE
[Enigma] Диспоз

### ISSUE THREAD

**Issue by pavel-b-novikov** [IvanProkopyev/nsudotnet#3]
Очень странно сделан. скажите, у вас не возникает ObjectDisposedException случаем при запуске шифровальщика? 
Заодно попытайтесь догадаться почему у меня возник такой вопрос.

**Comment by IvanProkopyev** [comment]
Подозреваю, потому что я захардкодил свой filepath для сохранения ключа?)

**Comment by IvanProkopyev** [comment]
А, ну и еще из-за проверки на наличие outputfile, которого может и не быть

**Comment by pavel-b-novikov** [comment]
Нет, ответ вот вообще ни разу не в кассу. Копайте глубже.

**Comment by IvanProkopyev** [comment]
а, из-за того, что есть и using  и close?

**Comment by pavel-b-novikov** [comment]
Опять нет

**Comment by IvanProkopyev** [comment]
задиспозил ICryptotransform, и всякие Des, aes и тд.

**Comment by pavel-b-novikov** [comment]
И снова нет.

**Comment by IvanProkopyev** [comment]
а не сами ли классы encryptor и decryptor нужно диспозить? ведь мы их только раз используем.

**Comment by pavel-b-novikov** [comment]
Слушайте, ну вы хоть почитайте что такое ObjectDisposedException

**Comment by IvanProkopyev** [comment]
Исправил, посмотрите, пожалуйста.

**Comment by pavel-b-novikov** [comment]
Слушайте, от вас не требовалось исправлять. От вас требовалось сказать что в этом коде может привести к ObjectDisposedException

**Comment by pavel-b-novikov** [comment]
Даже не что может к нему привести, а изучить что такое ObjectDisposedException и найти конструкцию в вашем коде, которая очень похожа на приводящую к нему.

**Comment by IvanProkopyev** [comment]
скорее всего там, где я в первом юзинге проверял тип кодирования.Ну а вообще этот эксепшн выбрасывается тогда, когда мы хотим обратиться к удаленному экземпляру  объекта, который является IDisposible.

**Comment by IvanProkopyev** [comment]
ну либо когда мы работаем с потоками, а файлы, связанные с ними внезапно были удалены, но такое маловероятно

**Comment by IvanProkopyev** [comment]
либо когда в using вызывал close

**Comment by pavel-b-novikov** [comment]
Мда. Вы самого очевидного не видите.

```
using (DESCryptoServiceProvider des = new DESCryptoServiceProvider()) {
                        des.Key = Key;
                        des.IV = IV;
                        decryptor = des.CreateDecryptor(des.Key, des.IV);
                    }
```

Сущность, породившую Decryptor вы убили, а сам декриптор продолжаете использовать как ни в чем не бывало. Эта ситуация обычно ведет к возникновению ObjectDisposedException, но в данном случае вам чертовски везет в силу особенностей реализации криптопровайдеров в Windows. В случае если вы такую фигню будете писать например, в DirectShow, то будете долго втыкать что пошло не так.

**Comment by IvanProkopyev** [comment]
а, понял, спасибо

**Comment by IvanProkopyev** [comment]
исправил

**Comment by pavel-b-novikov** [comment]
И что вы исправили? Не, вы по ходу дела не въехали в то, что я написал.

**Comment by IvanProkopyev** [comment]
Исправил cryptoserviceprovider

**Comment by pavel-b-novikov** [comment]
Я не понял, а сам CSP чтоли диспозить не надо? Сам умрет когда-нибудь?

**Comment by IvanProkopyev** [comment]
исправил.

**Comment by pavel-b-novikov** [comment]
Слушайте, вы прикалываетесь или как? Половина вариантов в свитчах старая, половина - новая. .Dispose выдывается явно, без try-finally. Вы чушь какую-то поправили. Переделайте нормально.

**Comment by IvanProkopyev** [comment]
то есть сделать все варианты в свичах с using?
так у меня .Dispose в явную вызывается в конце. Или Вы не про то?

**Comment by IvanProkopyev** [comment]
Когда using же используется, то не обязательно вызывать dispose в явную.

**Comment by IvanProkopyev** [comment]
Понял, почему там была критическая секция, сделал нормально - добавил в using.

**Comment by pavel-b-novikov** [comment]
Во-первых именование.
Во-вторых, у вас опять textreader через .Close используется.

**Comment by IvanProkopyev** [comment]
исправил именование, textreader занес в using
